on: [push]

jobs:
  get-maven-info:
    runs-on: ubuntu-latest
    name: maven-info
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Info Project
        uses: ./ # Uses an action in the root directory
        id: maven-info
      - name: Get the output Bet
        run: echo " The Version is: ${{ steps.maven-info.outputs.version }} "  
      - run: echo " The ArtifactId is: ${{ steps.maven-info.outputs.artifactId }}" 
      - run: echo " The groupId is:  ${{ steps.maven-info.outputs.groupId }} " 